spring:
  bot:
    plugin-list:
      # [BotPlugin]对应[私聊消息&群聊消息]插件
      - com.hybridsakura.project.plugins.BotPlugin_Log # 日志插件
      # [PrivatePlugin]对应[私聊消息]插件
      - com.hybridsakura.project.plugins.PrivatePlugin_MiyakoTest # 喵都测试 - 私聊版
      # [GroupPlugin]对应[群聊消息]插件
#      - com.hybridsakura.project.plugins.GroupPlugin_MiyakoTest # 喵都测试 - 群聊版
#      - com.hybridsakura.project.plugins.GroupPlugin_LuminaMain # Lumina主要功能（差不多了？）
#      - com.hybridsakura.project.plugins.GroupPlugin_LuminaOrder # Lumina指令系统（在建）
      - com.hybridsakura.project.plugins.GroupPlugin_Minecraft # MC建造指令生成器
#      - com.hybridsakura.project.plugins.GroupPlugin_SpecificRespond


server:
  # 端口号更改可能会导致lorca版无法连接到机器人
  port: 8081

logging:
  file:
    name: logs/luminabot.log

